from pygame.font import Font

DEFAULT_SHOW_FPS_COUNTER = True
DEFAULT_SHOW_STEPS_COUNTER = False
DEFAULT_START_PAUSED = False
DEFAULT_TARGET_STEPS_PER_SECOND = 50

DEFAULT_TARGET_ASPECT_RATIO = [16, 9]
DEFAULT_TARGET_WINDOW_WIDTH = 1280
DEFAULT_TARGET_FPS = 60
DEFAULT_TARGET_MONITOR_NUM = 1

DEFAULT_WALL_COLOUR = [11, 31, 50]
DEFAULT_SOLUTION_TILE_COLOUR = [135, 206, 235]
DEFAULT_BACKGROUND_COLOUR = [246, 250, 250]
DEFAULT_ENTRANCE_TILE_COLOUR = [68, 139, 68]
DEFAULT_EXIT_TILE_COLOUR = [191, 14, 8]

DEFAULT_FPS_COUNTER_COLOUR = [4, 4, 4]
DEFAULT_FPS_COUNTER_SIZE = 24 
DEFAULT_FPS_FONT = Font(None, DEFAULT_FPS_COUNTER_SIZE)


DEFAULT_STEP_COLOUR = [4, 4, 4]
DEFAULT_STEP_SIZE = 24 
DEFAULT_STEP_FONT = Font(None, DEFAULT_STEP_SIZE)